version: '3'

services:
  cadvisor:
    command: -housekeeping_interval=${HOUSEKEEPING_INTERVAL:-1s}
    hostname: cadvisor
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
  prometheus-app:
    build: .
    container_name: prometheus-app
    ports:
      - "8000:8000"
    environment:
      - NUM_METRICS=${NUM_METRICS:-10}
      - UPDATE_METRICS=${UPDATE_METRICS:-0}
    restart: unless-stopped
