global:
  scrape_interval: 15s
scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: app
  scrape_interval: 30s
  static_configs:
  - targets:
    - prometheus-app:8000
