# in this case we do not care about the app metrics, as these are read by the microview-nic client

global:
  scrape_interval: 15s
scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080

